fails:Array.new raises an ArgumentError when passed a negative size
fails:Array.new tries to convert the passed arguments to Arrays using #to_ary
fails:Array.new checks whether the passed argument responds to #to_ary
fails:Array.new checks whether the passed argument responds to #to_int if they don't respond to #to_ary
fails:Array.new calls to_ary on an argument before to_int
