fails:Kernel#callcc is a private method
fails:Kernel#callcc is possible to exit a loop like a break
fails:Kernel#callcc is possible to call a continuation multiple times
fails:Kernel#callcc returns the results of a block if block is not called
fails:Kernel#callcc returns the arguments to call
fails:Kernel#callcc preserves changes to block-local scope
fails:Kernel#callcc preserves changes to method-local scope
fails:Kernel#callcc raises a LocalJumpError if callcc is not given a block
fail:Kernel#callcc is a private method
fail:Kernel#callcc is possible to exit a loop like a break
fail:Kernel#callcc is possible to call a continuation multiple times
fail:Kernel#callcc returns the results of a block if block is not called
fail:Kernel#callcc returns the arguments to call
fail:Kernel#callcc preserves changes to block-local scope
fail:Kernel#callcc preserves changes to method-local scope
fail:Kernel#callcc raises a LocalJumpError if callcc is not given a block
