fails:Kernel.throw raises NameError if there is no catch block for the symbol
